using EtteplanMORE.ServiceManual.ApplicationCore.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace EtteplanMORE.ServiceManual.Infrastructure.Data
{
    public class MaintenanceTaskEntityConfiguration : IEntityTypeConfiguration<MaintenanceTask>
    {
        public void Configure(EntityTypeBuilder<MaintenanceTask> builder)
        {
            builder.ToTable("Maintenance Tasks");

            builder.HasKey(x => x.Id);
            builder.Property(x => x.Id).IsRequired(); //Auto-generated by EF Core on add

            builder.Property(x => x.TargetDevice);
            builder.Property(x => x.TimeRegistered).IsRequired();
            builder.Property(x => x.Description).IsRequired();
            builder.Property(x => x.SeverityLevel).IsRequired();
            builder.Property(x => x.CurrentStatus).IsRequired();
        }

    }
}